### ISSUE TITLE
Exception caused when creating an oslc-shape out of the shacl-shape class annotations - using JMH

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.validation#16]
The attribute "order" of a ShaclProperty is set to BigDecimal which is not support by oslc4J. This causes an exception OSLC005.

This occurs when trying to create an OSLC-resource-shape out of the class annotations on org.eclipse.lyo.validation.shacl.ShaclShape.

Caused by: org.eclipse.lyo.oslc4j.core.exception.OslcCoreInvalidPropertyTypeException: OSLC005: Invalid property type java.math.BigDecimal returned by method getOrder of class org.eclipse.lyo.validation.shacl.ShaclProperty
	at org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory.getDefaultValueType(ResourceShapeFactory.java:324)
	at org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory.createProperty(ResourceShapeFactory.java:219)
	at org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory.createResourceShape(ResourceShapeFactory.java:153)
	at org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory.createProperty(ResourceShapeFactory.java:300)

**Comment by berezovskyi** [comment]
What's the plan for this one? It is solved by your recent changes to the Designer types?

**Comment by jadelkhoury** [comment]
@yashkhatri can you confirm if/that issue is already dealt with?

**Comment by yashkhatri** [comment]
Yes. Resolved Fixed!
